export const SET_USER = 'SET_USER'
export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_FINISH = 'LOGIN_USER_FINISH'

export const LOGOUT_USER_START = 'LOGOUT_USER_START'
export const LOGOUT_USER_FINISH = 'LOGOUT_USER_FINISH'
export const REMOVE_USER = 'REMOVE_USER'

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_SUMMARY_START = 'GET_SUMMARY_START'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_FAILURE = 'GET_SUMMARY_FAILURE'

export const GET_NATIONALITIES_START = 'GET_NATIONALITIES_START'
export const GET_NATIONALITIES_SUCCESS = 'GET_NATIONALITIES_SUCCESS'
export const GET_NATIONALITIES_FAILURE = 'GET_NATIONALITIES_FAILURE'

export const GET_NATIONALITIES_HASH = 'GET_NATIONALITIES_HASH'

export const GET_USER_DETAILS_START = 'GET_USER_DETAILS_START'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_FINISH = 'UPDATE_USER_FINISH'

export const GET_RANKS = 'GET_RANKS'
export const GET_RANKS_START = 'GET_RANKS_START'
export const GET_RANKS_SUCCESS = 'GET_RANKS_SUCCESS'
export const GET_RANKS_FAILURE = 'GET_RANKS_FAILURE'

export const SET_LANGUAGE = 'SET_LANGUAGE'
